In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
c = np.random.randint(1, 11, size=(5, 5))
print(c)

[[ 2  4  1  3  4]
 [ 4  5  9  3  2]
 [ 9  3  6  8  8]
 [ 5 10  9  6 10]
 [ 6  4  2  8  5]]


In [7]:
d = np.random.uniform(0, 1, size=(4, 4))
print(d)

[[0.98652408 0.46851783 0.69985476 0.36543625]
 [0.5261993  0.79912653 0.23741251 0.3769747 ]
 [0.40533172 0.37364519 0.13016794 0.14586706]
 [0.05203466 0.37956971 0.73697061 0.31715403]]


In [8]:
e = np.random.randint(1, 11, size = 5 )
f = np.random.randint(1, 11, size = 5 )
print(e, f)
sum_e_f = e + f
diff_e_f = e - f
e_times_f = e * f
print(sum_e_f, diff_e_f, e_times_f)

[ 3  1 10  1  9] [10  1  3  2 10]
[13  2 13  3 19] [-7  0  7 -1 -1] [30  1 30  2 90]


In [9]:
g = np.random.random(7)
h = np.random.random(7)
print(g, h)
scal_g_times_h = np.dot(g, h)
print(scal_g_times_h)

[0.31699053 0.77508074 0.69396157 0.82685825 0.49739793 0.59859645
 0.13176668] [0.11682647 0.92540963 0.26625678 0.11395162 0.2014124  0.85742923
 0.01318262]
1.6484671129986093


In [10]:
i = np.random.randint(1, 11, size = (2, 2) )
j = np.random.randint(1, 11, size = (2, 3) )
print(i, j)
i_times_j = np.dot(i, j)
print( i_times_j )

[[ 8  4]
 [ 3 10]] [[3 5 1]
 [8 3 4]]
[[56 52 24]
 [89 45 43]]


In [11]:
k = np.random.randint(1, 11, size = (3, 3) )
print(k)
k_inv = np.linalg.inv(k)
print(k_inv)

[[7 8 6]
 [9 2 6]
 [1 6 3]]
[[ 0.45454545 -0.18181818 -0.54545455]
 [ 0.31818182 -0.22727273 -0.18181818]
 [-0.78787879  0.51515152  0.87878788]]


In [14]:
l = np.random.uniform(0, 1, size = (4, 4))
print(l)
transformed_l = l.T
print(transformed_l)

[[0.23686191 0.80765571 0.08129269 0.18058535]
 [0.00895435 0.43024446 0.92143021 0.74689414]
 [0.21418341 0.95675342 0.2469383  0.92205388]
 [0.80677006 0.58910161 0.55625021 0.7063523 ]]
[[0.23686191 0.00895435 0.21418341 0.80677006]
 [0.80765571 0.43024446 0.95675342 0.58910161]
 [0.08129269 0.92143021 0.2469383  0.55625021]
 [0.18058535 0.74689414 0.92205388 0.7063523 ]]


In [15]:
p = np.random.uniform(1, 11, size = (3,4))
q = np.random.uniform(1, 11, size = 4)
print(p, q)
p_times_q = np.dot(p, q)
print(p_times_q)

[[6.148415   2.67715766 6.86314526 1.86615705]
 [5.44870669 6.75008091 5.61711301 6.632202  ]
 [8.98557667 6.9896857  3.22564284 6.47182927]] [5.21148467 2.35105258 7.57071715 7.35365934]
[104.01852361 135.56217452 135.27337095]


In [16]:
p = np.random.uniform(0, 1, size = (2, 3))
q = np.random.uniform(0, 1, size = 3)
print(p, q)
p_times_q = np.dot(p, q)
print(p_times_q)

[[0.44631234 0.80650625 0.58889145]
 [0.74143455 0.25110045 0.62582188]] [0.20660505 0.02975572 0.18831203]
[0.22710391 0.27850559]


In [17]:
r = np.random.uniform(1, 11, size = (2, 2))
s = np.random.uniform(1, 11, size = (2, 2))
print(r, s)
r_times_s = r*s
print(r_times_s)

[[3.32049209 3.82197837]
 [7.56901741 6.58453297]] [[ 1.67289014  8.93032355]
 [10.17787757  1.11353964]]
[[ 5.55481847 34.13150348]
 [77.03653255  7.33213848]]


In [18]:
r = np.random.uniform(1, 11, size = (2, 2))
s = np.random.uniform(1, 11, size = (2, 2))
print(r, s)
r_times_s = np.dot(r, s)
print(r_times_s)

[[5.6275192  8.61346719]
 [3.49788124 5.45708959]] [[7.90815087 7.5206732 ]
 [9.65051301 2.4107565 ]]
[[127.62764806  63.08770484]
 [ 80.32548674  39.46213591]]


In [19]:
t = np.random.uniform(1, 101, size = (5, 5))
print(t)
sum = 0
for i in t:
  for c in i:
    sum += c
print(sum)


[[ 48.61790548  25.2808677   41.40240317  65.49734026  35.00371545]
 [  7.89529011  55.63615894  52.07851407  76.29899333  58.21987306]
 [ 53.94063755  21.61877297  69.99858307 100.8044941   99.32408154]
 [ 27.60522032  94.69397064  16.7349779   26.59915769  89.17961419]
 [ 91.72532576  46.94177913  22.99247176  72.28307283   6.79232936]]
1307.1655503606382


In [20]:
u = np.random.uniform(1, 11, size = (4, 4))
v = np.random.uniform(1, 11, size = (4, 4))
print(u, v)
diff_u_v = u - v
print(diff_u_v)

[[ 3.15582702  6.57727285  6.56147427  4.96078298]
 [ 9.5011059   7.78855737  3.76015352  4.67606512]
 [ 1.74941379  4.97783443  9.22876103 10.64855288]
 [ 5.25090808  2.35804398  8.34032209  8.44966926]] [[ 9.75143566  3.84868493  3.86817588  8.12189204]
 [ 9.9447623   1.39067255  8.66533763  2.37734304]
 [ 3.77478756 10.16065234  2.66790986  6.8106658 ]
 [ 8.21202613  9.90209879  9.57308764  5.49989852]]
[[-6.59560864  2.72858792  2.69329839 -3.16110906]
 [-0.4436564   6.39788482 -4.90518411  2.29872208]
 [-2.02537376 -5.18281792  6.56085116  3.83788708]
 [-2.96111806 -7.54405481 -1.23276555  2.94977075]]


In [21]:
a = np.random.uniform(0, 1 , size = (3, 3))
print(a)
sum_vector = np.sum(a, axis=1)
e = sum_vector.reshape(-1, 1)
print(e)

[[0.0608012  0.05594028 0.3009003 ]
 [0.52592066 0.91017737 0.61565244]
 [0.72246227 0.84032643 0.90566726]]
[[0.41764178]
 [2.05175047]
 [2.46845597]]


In [22]:
a = np.random.randint(0, 99999, size = (3, 4))
print(a)
b = a**2
print(b)

[[42505 99450 55546 20781]
 [82423 39657 24638 70427]
 [78965 33170  7434 12984]]
[[ 1806675025  1300367908 -1209609180   431849961]
 [-1796383663  1572677649   607031044   664995033]
 [ 1940503929  1100248900    55264356   168584256]]


In [23]:
a = np.random.randint(1, 51, size = 4)
print(a)
b = np.sqrt(a)
print(b)

[13 13 32 17]
[3.60555128 3.60555128 5.65685425 4.12310563]
